### ISSUE TITLE
Style popup overlay

### ISSUE THREAD

**Issue by Woosaki** [deliskyxd/Cinema-Map#3]
Correctly style onclick overlay on each cinema so it's a nice looking bubble.

**Comment by deliskyxd** [comment]
There needs to be a function that checks for example whethever the point is above the half of the page because if not then it can't be seen properly

**Comment by deliskyxd** [comment]
-Add properties to the window so that it doesn't close after clicking on it, and makes it possible to copy from it/ interact with it.
